SugarCube/Models/Comment.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace SugarCube.Models
{
    public class Comment
    {
        public string Text { get; set; }
        public User Author { get; set; }
        public DateTime Timestamp { get; set; }
        public IEnumerable<Comment> Comments { get; set; }

        public Comment()
        {
            Comments = new Comment[] { };
        
        }
    }
}

SugarCube/Models/CubeViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SugarCube.Models
{
    public class CubeViewModel
    {
        public List<JournalEntry> JournalEntries { get; set; }

        public SelectListItem[] Tags { get; set; }

        public SelectListItem[] Permissions { get; set; }
    }
}

SugarCube/Controllers/CubeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SugarCube.Models;

namespace SugarCube.Controllers
{
    public class CubeController : Controller
    {
        //
        // GET: /Cube/

        private void Initialize(out List<JournalEntry> cubes, out  SelectListItem[] tags, out  SelectListItem[] permissions)
        {
            cubes = new List<JournalEntry>(){
                new JournalEntry{ Title = "Hello World 1", Date=DateTime.Today, Text = "This is a short message.", Type="journal" },
                new JournalEntry{ Title = "Hello World 2", Date=DateTime.Today, Text = "This is a somewhat longer message.", Type="other" },
                new JournalEntry{ Title = "Hello World 3", Date=DateTime.Today, Text = "This is a message with an image.", Image = "~/Content/Images/7.jpg", Type="journal"},
                new JournalEntry{ Title = "Hello World 4", Date=DateTime.Today, Image = "~/Content/Images/4.jpg", Type="journal" },
                new JournalEntry{ Title = "Hello World 5", Date=DateTime.Today, Text = "This is a short message.", Type="other" },
                new JournalEntry{ Title = "Hello World 6", Date=DateTime.Today, Text = "This is a somewhat longer message.", Type="journal" },
                new JournalEntry{ Title = "Hello World 7", Date=DateTime.Today, Image = "~/Content/Images/6.jpg", Type="journal" },
                new JournalEntry{ Title = "Hello World 8", Date=DateTime.Today, Text = "This is a short message.", Type="other" },
                new JournalEntry{ Title = "Hello World 9", Date=DateTime.Today, Text = "This is a somewhat longer message.", Type="journal" },
                new JournalEntry{ Title = "Hello World 10", Date=DateTime.Today, Text = "This is a short message.", Type="journal" },
                new JournalEntry{ Title = "Hello World 11", Date=DateTime.Today, Text = "This is a somewhat longer message.", Type="other" },
                new JournalEntry{ Title = "Hello World 12", Date=DateTime.Today, Text = "This is a message with an image.", Image = "~/Content/Images/3.jpg", Type="journal"},
                new JournalEntry{ Title = "Hello World 13", Date=DateTime.Today, Text = @"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed a dapibus lorem. Etiam vel enim vel justo aliquet tempus quis id orci. In ultricies, purus vel adipiscing cursus, nulla nunc luctus ligula, eu faucibus est velit ornare leo. Suspendisse vehicula purus eu nisi mattis vestibulum. Nulla facilisi. Mauris imperdiet aliquet urna, eget gravida dolor lacinia eu. Pellentesque sodales consectetur ante vel consequat. Proin fringilla consectetur dui, sit amet lobortis nulla placerat sodales. Aliquam a facilisis neque. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Suspendisse ac leo nec eros malesuada ultricies sed at ipsum.

Fusce sit amet purus et mauris congue mattis sed ut arcu. Praesent faucibus libero sed nulla imperdiet sagittis. Aenean ac magna in risus ullamcorper pulvinar at ut nulla. Phasellus volutpat risus id leo pretium eget venenatis nibh dapibus. Morbi eget dolor dolor. Suspendisse potenti. Aenean vitae diam at purus mattis suscipit sit amet a nibh. Phasellus condimentum rutrum iaculis. Suspendisse accumsan, velit luctus congue condimentum, libero magna pretium sapien, ac semper mi est quis arcu. Duis ultricies lectus id metus pulvinar et consectetur mauris lobortis. Suspendisse purus turpis, condimentum sed commodo sed, vestibulum et velit. Praesent in neque neque. Etiam ullamcorper aliquam nisl a varius. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.

Vivamus feugiat rhoncus arcu, eu molestie felis tristique vel. Proin congue lobortis elit eu porttitor. Praesent magna ante, placerat nec elementum at, pretium ac lacus. Aliquam lacus est, fermentum quis feugiat eget, rutrum id mi. Morbi placerat nibh a nulla congue consequat. Morbi elementum metus sit amet mauris sodales nec pharetra magna cursus. Praesent egestas dolor et diam dapibus cursus vulputate eros pharetra. Donec adipiscing lectus sed odio ultricies tristique. Duis ac tortor nulla. Mauris elementum lorem sit amet est molestie elementum.

Quisque sit amet libero non diam sodales lacinia a a mauris. Nam sit amet velit magna, at feugiat lectus. Morbi tellus neque, lacinia vel rutrum vitae, feugiat sit amet turpis. Mauris varius, lorem at ultrices eleifend, sem enim convallis nulla, at fermentum leo odio ut neque. Duis et nisi leo, eget euismod ipsum. Etiam viverra suscipit urna nec placerat. Quisque viverra gravida vulputate. Nullam posuere volutpat convallis. Nullam dapibus consequat ornare. Morbi eros ante, fringilla ut scelerisque at, molestie non felis.

In hac habitasse platea dictumst. Praesent ut massa ut odio facilisis lobortis. Suspendisse odio mi, adipiscing id lobortis at, varius vel eros. Nullam scelerisque lobortis dolor sit amet commodo. Duis et dui turpis, vel luctus ante. Donec in hendrerit lacus. Phasellus ut mauris ac nisl mollis iaculis ut ultricies arcu. Cras rhoncus neque ac augue iaculis dictum.", Image = "~/Content/Images/4.jpg", Type="journal"},
                new JournalEntry{ Title = "Hello World 14", Date=DateTime.Today, Text = "Sed elit leo, fringilla at varius at, iaculis vitae felis. Nunc pulvinar enim ac augue suscipit accumsan. Vestibulum ullamcorper euismod sagittis. Pellentesque risus purus, auctor eget dignissim ac, rutrum sit amet nunc. Fusce vehicula arcu vitae quam luctus tincidunt. Nullam ac orci interdum eros tempor ullamcorper eu vitae metus. Aliquam non enim ut purus rhoncus tempus.", Image = "~/Content/Images/2.jpg", Type="journal"}
            };

            permissions = new SelectListItem[] {
                new SelectListItem{ Text = "friends & strangers", Value = "5"},
                new SelectListItem{ Text = "maybe friends", Value = "4"},
                new SelectListItem{ Text = "just friends", Value = "3"},
                new SelectListItem{ Text = "dear best friends", Value = "2" },
                new SelectListItem{ Text = "my eyes only", Value = "1" },
                new SelectListItem{ Text = "friends & strangers", Value = "5"},
                new SelectListItem{ Text = "maybe friends", Value = "4"},
                new SelectListItem{ Text = "just friends", Value = "3"},
                new SelectListItem{ Text = "dear best friends", Value = "2" },
                new SelectListItem{ Text = "my eyes only", Value = "1" }
            };


            Random rand = new Random();
            var tagsList = new List<SelectListItem>();
            for (int i = 1; i <= 30; i++)
            {
                switch (rand.Next(1, 3))
                {
                    case 1:
                        tagsList.Add(new SelectListItem { Text = "cat " + i, Value = i.ToString() });
                        break;
                    case 2:
                        tagsList.Add(new SelectListItem { Text = "calvin & hobbes " + i, Value = i.ToString() });
                        break;
                    case 3:
                        tagsList.Add(new SelectListItem { Text = "elephant " + i, Value = i.ToString() });
                        break;
                }
            };

            tags = tagsList.ToArray();
        }

        public ActionResult Index()
        {
            List<JournalEntry> cubes;
            SelectListItem[] tags;
            SelectListItem[] permissions;
            Initialize(out cubes, out tags, out permissions);
            return View(new CubeViewModel() { JournalEntries = cubes, Tags = tags, Permissions = permissions });
        }

        public ActionResult GetCubes()
        {
            return View();
        }

        [HttpPost]
        [ValidateInput(false)]
        public ActionResult CreateJournal(FormCollection form)
        {
            List<JournalEntry> cubes;
            SelectListItem[] tags;
            SelectListItem[] permissions;
            Initialize(out cubes, out tags, out permissions);
            return View("Index", new CubeViewModel() { JournalEntries = cubes, Tags = tags, Permissions = permissions });
        }

        public ActionResult CubeTest()
        {
            return View();
        }

        public ActionResult Journal()
        {
            JournalEntry viewModel = new JournalEntry
            {
                Author = new User { Id = 1, Name = "silverangel" },
                Date = DateTime.Today,
                Text = "<p>Lorem ipsum dolor sit amet,<br/><br/> consectetur adipiscing elit. Duis semper lorem sit amet sapien egestas tincidunt. Nam sed nulla vitae massa rutrum tristique ac at dolor. Fusce aliquet sapien eu metus tempus eu vulputate nisl cursus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nam consequat dui vitae felis lacinia vel elementum tellus vulputate. Nam justo leo, sagittis sed laoreet at, congue eget urna. Phasellus vulputate diam in velit volutpat sed congue quam tempus. Aliquam erat volutpat. Proin auctor tempor varius. Nulla iaculis velit in ligula tincidunt volutpat. Praesent at nunc sed mauris fermentum aliquet.<br/><br/> <strong>What can I do? Should I keep waiting or move on?</strong></p>",
                Title = "Should I Text Him?",
                Type = "journal",
                Comments = new Comment[] {
                    new Comment
                    {
                        Text="I am so sorry to hear that!",
                        Author = new User{ Name="purplepig", Gender= GenderType.Female},
                        Timestamp = DateTime.Today, 
                        Comments = new Comment[]
                        {
                       
                            new Comment
                            {
                                Text="hahaha girls are silly",

SugarCube/Views/Cube/Comment.cshtml
@using SugarCube.Models
@model Comment

<div class="comment row-fluid ">

 
        <div class="profile ">
            <img src="@Url.Content("~/Content/images/profile.png")" />
        </div>
        <div class="content @Model.Author.Gender.ToString().ToLower()" style="position: relative;">
            <button class="btn" style="position: absolute; right: 0px; bottom: 0px;">Reply</button>
            <div class="bubble">
                <p>@Html.Raw(Model.Text)</p>
                says <a href="#">@Model.Author.Name</a> on @Model.Timestamp.ToString("MM/d/yyyy hh:mm tt")
            </div>
        </div>
        <div class="comments">
            @foreach (Comment comment in Model.Comments)
            {
                @Html.Partial("Comment", comment)
            }
        </div>

</div>

SugarCube/Views/Cube/Cube.cshtml
@model SugarCube.Models.JournalEntry

@helper CalculateSize(string text, string image)
{
    //Some algorithm to calculate cube size
    if (!String.IsNullOrEmpty(text) && text.Length > 25)
    {
    <text>h-2</text>
    }
    else
    {
    <text>h-1</text>
    }
    if (!String.IsNullOrEmpty(image))
    {
    <text> v-2</text>
    }
    else
    {
    <text> v-1</text>
    }
}

<div class="item cube @CalculateSize(Model.Text, Model.Image) @Model.Type" data-source="@Url.Action("Journal","Cube")">
      <i class="icon-heart pull-right" style="color: #FFEEFB;"></i>
   <div class="inner">
     
    @if (!String.IsNullOrEmpty(Model.Image))
    {
        <img src="@Url.Content(Model.Image)" /><br />
    }
    <span class="title">@Model.Title</span><br />
    <span class="date">@Model.Date.ToString("d MMM yyyy")</span><br />
      
    <div class="text">@Model.Text</div>
   </div>
</div>

SugarCube/Views/Cube/CubeTest.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>CubeTest</title>
@Styles.Render("~/Content/bootstrap")
    @Styles.Render("~/Content/css")
    @Styles.Render("~/Content/chosen")
</head>
<body>
    <div class="container-fluid">
          <div class="row-fluid">
               <form>
                <div class="input-append">
                   
                    <input type="text" class="pink input-small" style="font-size: 20px;" value="@DateTime.Today.ToString("dd MMM yy")">
                    
                    <div class="btn-group">
                        <button class="btn dropdown-toggle" data-toggle="dropdown"><i class="icon-filter"></i><span class="caret"></span></button>
                       @* <ul class="dropdown-menu" role="menu" aria-labelledby="dropdownMenu">
                            <li><a tabindex="-1" href="#">Date</a></li>
                            <li><a tabindex="-1" href="#">Most comments</a></li>
                            <li><a tabindex="-1" href="#">Most nods</a></li>
                            <li><a tabindex="-1" href="#">Magic</a></li>
                        </ul>*@
                    </div>
                         
                </div>
                  </form>
                <div class="btn-group span12" data-toggle="buttons-radio">
                  <button type="button" class="btn"><i class="icon-briefcase"></i></button>
                  <button type="button" class="btn"><i class="icon-bullhorn"></i></button>
                  <button type="button" class="btn"><i class="icon-asterisk"></i></button><br />
                  <button type="button" class="btn"><i class="icon-briefcase"></i></button>
                  <button type="button" class="btn"><i class="icon-bullhorn"></i></button>
                  <button type="button" class="btn"><i class="icon-asterisk"></i></button>
                </div>

              
                <select id="tagfilter" multiple="multiple" data-placeholder="tags">
                    <option>long distance</option>
                    <option>breakups</option>
                    <option>heartbreaks</option>
                    <option>flowers</option>
                    <option>--------</option>
                    <option>view all</option>
                </select>
                <button class="btn"><i class="icon-caret-right"></i></button>
              
                  
      
          </div>

        <div>
            <i class="sc-icon-sm-happy"></i>
            <i class="sc-menuicon-profile"></i><br />
            <i class="sc-menuicon-mycube"></i><br />
            <i class="sc-menuicon-sweethearts"></i><br />
            <i class="sc-menuicon-sugarline"></i><br />
            <div>
                <i class="icon-book" style="color: #999; font-size: 24px;"></i>
                <i class="icon-pencil" style="position: relative; left: -18px; top:3px; color: green; font-size: 20px;"></i>
            </div>
            <i class="icon-comments" style="font-size: 24px;"></i>
        </div>
    </div>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/chosen")
    <script type="text/javascript">
        $("#tagfilter").chosen();
    </script>
</body>
</html>

SugarCube/Views/Cube/Index.cshtml
@using SugarCube.Models
@model CubeViewModel
@{
    ViewBag.Title = "SugarCube";
}

<div id="cubes">
    @foreach (JournalEntry entry in Model.JournalEntries)
    {
        Html.RenderPartial("Cube", entry);
    }
</div>

@section scripts
{

    <script type="text/javascript">
        $(function () {
            var $container = $("#cubes");

            $container.isotope({
                itemSelector: '.item',
                layoutMode: 'masonry'
            });

            // filter items when filter link is clicked
            $('#filters a').on("click", function () {
                var selector = $(this).attr('data-filter');
                $container.isotope({ filter: selector });
                $('#filters li').removeClass("active");
                $(this).closest("li").addClass("active");
            });

        });

    </script>
}

SugarCube/Views/Cube/Journal.cshtml
@using SugarCube.Models

@model JournalEntry

@{
    Layout = "~/Views/Shared/_LayoutSimple.cshtml";
    //Layout = null;
}

<h2>@Model.Title</h2>


<i class="sc-menuicon-profile"></i><a href="#">@Model.Author.Name</a>&nbsp;|&nbsp;@Model.Date.ToString("d MMM yyyy")



<br />
@Html.Raw(Model.Text)

<div class="row-fluid actions">
    <div class="span3">
        <i class="sc-scicon-nod"></i><a href="#">nod nod!</a>
    </div>
    <div class="span9">
        Share this <a class="btn btn-mini"><i class="icon-envelope"></i></a>&nbsp;<a class="btn btn-mini"><i class="icon-twitter"></i></a>&nbsp;<a class="btn btn-mini"><i class="icon-facebook"></i></a>&nbsp;<a class="btn btn-mini"><i class="icon-google-plus"></i></a>
    </div>
</div>
<div class="row-fluid">
    <strong>Comments: @Model.CommentCount &nbsp;&nbsp;&nbsp; Nods: @Model.NodCount</strong>
</div>
<div class="row-fluid">
    @foreach (Comment comment in Model.Comments)
    {
        @Html.Partial("Comment", comment)
    }
</div>